# Generated by Django 3.2.19 on 2025-06-13 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adkrity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('type', models.CharField(db_index=True, max_length=20)),
                ('weight', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('meta_data', models.JSONField(blank=True, default=None, null=True)),
                ('approved_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('approved_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('related_tags', models.ManyToManyField(blank=True, related_name='_adkrity_tagmaster_related_tags_+', to='adkrity.TagMaster')),
                ('synonyms', models.ManyToManyField(blank=True, related_name='_adkrity_tagmaster_synonyms_+', to='adkrity.TagMaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
