# Generated by Django 3.2.19 on 2025-07-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkrity', '0002_mediatypemaster_tagmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdKrityTagMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('meta_data', models.JSONField(blank=True, default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tagmaster',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='tagmaster',
            name='related_tags',
        ),
        migrations.RemoveField(
            model_name='tagmaster',
            name='synonyms',
        ),
    ]
