# Generated by Django 3.2.19 on 2025-07-01 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0002_alter_designermedia_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adkrity', '0003_auto_20250701_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagMaster',
        ),
        migrations.AddField(
            model_name='adkritytagmaster',
            name='added_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
