# Generated by Django 3.2.19 on 2025-06-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adkrity', '0002_mediatypemaster_tagmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerFontMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('font_file', models.FileField(blank=True, default=None, null=True, upload_to='dfonts')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DesignerMediaCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DesignerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified date')),
                ('source', models.CharField(max_length=100)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='dm', verbose_name='Image (Jpg or Png)')),
                ('media', models.FileField(blank=True, default=None, null=True, upload_to='dm', verbose_name='Vector (Psd)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='designers.designermediacategories')),
                ('media_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adkrity.mediatypemaster')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adkrity.tagmaster')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
