# Generated by Django 3.2.19 on 2025-07-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkrity', '0003_auto_20250701_1859'),
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designermedia',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adkrity.adkritytagmaster'),
        ),
    ]
