# Generated by Django 3.2.19 on 2025-03-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0022_userstoryhourlypendingwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStoryHourlyPendingWork',
        ),
    ]
