# Generated by Django 3.2.19 on 2024-12-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0009_finalattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalattachment',
            options={'ordering': ['project', 'created_date', 'id'], 'verbose_name': 'final attachment', 'verbose_name_plural': 'final attachments'},
        ),
    ]
